// GENERATED by scripts/generate-swift-battle-shapes.mjs from
// src/data/battleShapes.js — do not edit by hand. Run
// `npm run ios:battle-shapes` after changing the JavaScript shapes.

extension BattleShape {
    /// Every shape in the library, in the JavaScript `BATTLE_SHAPES` order.
    public static let all: [BattleShape] = [
        BattleShape(
            id: "diamond", name: "Diamond",
            cells: 13, width: 5, height: 5,
            art: """
            ..X..
            .XXX.
            XXXXX
            .XXX.
            ..X..
            """
        ),
        BattleShape(
            id: "diamond-mini", name: "Mini Diamond",
            cells: 5, width: 3, height: 3,
            art: """
            .X.
            XXX
            .X.
            """
        ),
        BattleShape(
            id: "hexagon", name: "Hexagon",
            cells: 16, width: 5, height: 4,
            art: """
            .XXX.
            XXXXX
            XXXXX
            .XXX.
            """
        ),
        BattleShape(
            id: "plus", name: "Plus",
            cells: 9, width: 5, height: 5,
            art: """
            ..X..
            ..X..
            XXXXX
            ..X..
            ..X..
            """
        ),
        BattleShape(
            id: "plus-big", name: "Big Plus",
            cells: 13, width: 7, height: 7,
            art: """
            ...X...
            ...X...
            ...X...
            XXXXXXX
            ...X...
            ...X...
            ...X...
            """
        ),
        BattleShape(
            id: "cross-x", name: "X Cross",
            cells: 9, width: 5, height: 5,
            art: """
            X...X
            .X.X.
            ..X..
            .X.X.
            X...X
            """
        ),
        BattleShape(
            id: "heart", name: "Heart",
            cells: 16, width: 5, height: 5,
            art: """
            .X.X.
            XXXXX
            XXXXX
            .XXX.
            ..X..
            """
        ),
        BattleShape(
            id: "flower", name: "Flower",
            cells: 17, width: 5, height: 5,
            art: """
            .X.X.
            XXXXX
            .XXX.
            XXXXX
            .X.X.
            """
        ),
        BattleShape(
            id: "sun", name: "Sun",
            cells: 17, width: 5, height: 5,
            art: """
            X.X.X
            .XXX.
            XXXXX
            .XXX.
            X.X.X
            """
        ),
        BattleShape(
            id: "moon-crescent", name: "Crescent Moon",
            cells: 12, width: 5, height: 5,
            art: """
            .XXX.
            XX...
            XX...
            XX...
            .XXX.
            """
        ),
        BattleShape(
            id: "butterfly", name: "Butterfly",
            cells: 19, width: 5, height: 5,
            art: """
            X.X.X
            XXXXX
            .XXX.
            XXXXX
            X.X.X
            """
        ),
        BattleShape(
            id: "bee-stripes", name: "Bee Stripes",
            cells: 18, width: 5, height: 5,
            art: """
            .XXX.
            XXXXX
            .X.X.
            XXXXX
            .XXX.
            """
        ),
        BattleShape(
            id: "tree", name: "Tree",
            cells: 14, width: 5, height: 6,
            art: """
            ..X..
            .XXX.
            XXXXX
            .XXX.
            ..X..
            ..X..
            """
        ),
        BattleShape(
            id: "mushroom", name: "Mushroom",
            cells: 15, width: 5, height: 5,
            art: """
            .XXX.
            XXXXX
            XXXXX
            ..X..
            ..X..
            """
        ),
        BattleShape(
            id: "leaf", name: "Leaf",
            cells: 15, width: 5, height: 5,
            art: """
            ....X
            ..XXX
            .XXXX
            XXXX.
            XXX..
            """
        ),
        BattleShape(
            id: "cloud", name: "Cloud",
            cells: 23, width: 7, height: 4,
            art: """
            .XX.XX.
            XXXXXXX
            XXXXXXX
            .XXXXX.
            """
        ),
        BattleShape(
            id: "mountain", name: "Mountain",
            cells: 16, width: 7, height: 4,
            art: """
            ...X...
            ..XXX..
            .XXXXX.
            XXXXXXX
            """
        ),
        BattleShape(
            id: "wave", name: "Wave",
            cells: 14, width: 7, height: 3,
            art: """
            XX...XX
            XXXXXXX
            ..XXX..
            """
        ),
        BattleShape(
            id: "fish", name: "Fish",
            cells: 17, width: 7, height: 3,
            art: """
            .XXXX.X
            XXXXXXX
            .XXXX.X
            """
        ),
        BattleShape(
            id: "gem", name: "Gem",
            cells: 15, width: 5, height: 5,
            art: """
            .XXX.
            XXXXX
            .XXX.
            .XXX.
            ..X..
            """
        ),
        BattleShape(
            id: "crystal", name: "Crystal",
            cells: 14, width: 3, height: 6,
            art: """
            .X.
            XXX
            XXX
            XXX
            XXX
            .X.
            """
        ),
        BattleShape(
            id: "honeycomb", name: "Honeycomb",
            cells: 17, width: 5, height: 5,
            art: """
            .X.X.
            XXXXX
            X.X.X
            XXXXX
            .X.X.
            """
        ),
        BattleShape(
            id: "star", name: "Star",
            cells: 15, width: 5, height: 5,
            art: """
            ..X..
            XXXXX
            .XXX.
            XX.XX
            X...X
            """
        ),
        BattleShape(
            id: "crown", name: "Crown",
            cells: 22, width: 7, height: 4,
            art: """
            X..X..X
            X.XXX.X
            XXXXXXX
            XXXXXXX
            """
        ),
        BattleShape(
            id: "arrow-up", name: "Arrow Up",
            cells: 11, width: 5, height: 5,
            art: """
            ..X..
            .XXX.
            XXXXX
            ..X..
            ..X..
            """
        ),
        BattleShape(
            id: "ring", name: "Ring",
            cells: 12, width: 5, height: 5,
            art: """
            .XXX.
            X...X
            X...X
            X...X
            .XXX.
            """
        ),
        BattleShape(
            id: "staircase", name: "Staircase",
            cells: 12, width: 6, height: 4,
            art: """
            XXX...
            .XXX..
            ..XXX.
            ...XXX
            """
        ),
        BattleShape(
            id: "anchor-t", name: "Anchor (I-beam)",
            cells: 13, width: 5, height: 5,
            art: """
            XXXXX
            ..X..
            ..X..
            ..X..
            XXXXX
            """
        ),
        BattleShape(
            id: "letter-h", name: "Letter H",
            cells: 13, width: 5, height: 5,
            art: """
            X...X
            X...X
            XXXXX
            X...X
            X...X
            """
        ),
        BattleShape(
            id: "zigzag-z", name: "Zigzag Z",
            cells: 15, width: 5, height: 5,
            art: """
            XXXXX
            ...XX
            ..X..
            XX...
            XXXXX
            """
        ),
        BattleShape(
            id: "triangle-up", name: "Triangle Up",
            cells: 9, width: 5, height: 3,
            art: """
            ..X..
            .XXX.
            XXXXX
            """
        ),
        BattleShape(
            id: "triangle-down", name: "Triangle Down",
            cells: 9, width: 5, height: 3,
            art: """
            XXXXX
            .XXX.
            ..X..
            """
        ),
        BattleShape(
            id: "letter-l", name: "Letter L",
            cells: 5, width: 3, height: 3,
            art: """
            X..
            X..
            XXX
            """
        ),
        BattleShape(
            id: "letter-t", name: "Letter T",
            cells: 5, width: 3, height: 3,
            art: """
            XXX
            .X.
            .X.
            """
        ),
        BattleShape(
            id: "bowtie", name: "Bowtie",
            cells: 5, width: 3, height: 3,
            art: """
            X.X
            .X.
            X.X
            """
        ),
        BattleShape(
            id: "chevron", name: "Chevron",
            cells: 5, width: 5, height: 3,
            art: """
            X...X
            .X.X.
            ..X..
            """
        ),
        BattleShape(
            id: "kite-small", name: "Small Kite",
            cells: 6, width: 3, height: 4,
            art: """
            .X.
            XXX
            .X.
            .X.
            """
        ),
        BattleShape(
            id: "boat", name: "Boat",
            cells: 8, width: 5, height: 2,
            art: """
            .XXX.
            XXXXX
            """
        ),
        BattleShape(
            id: "acorn", name: "Acorn",
            cells: 7, width: 3, height: 3,
            art: """
            XXX
            XXX
            .X.
            """
        ),
        BattleShape(
            id: "berries", name: "Berries",
            cells: 7, width: 5, height: 2,
            art: """
            .X.X.
            XXXXX
            """
        ),
    ]
}
