// GENERATED by scripts/generate-swift-game-catalog.mjs from
// src/data/games.js — do not edit by hand. Run
// `npm run ios:game-catalog` after changing the JavaScript catalog.

extension LairSubject {
    /// The lair's front door, in the JavaScript `SUBJECTS` order.
    public static let all: [LairSubject] = [
        LairSubject(
            id: "math", label: "Math", emoji: "🔢",
            blurb: "Facts, drills and races — plus, minus, times, divide.", color: 0x6F96B8),
        LairSubject(
            id: "spelling", label: "Spelling", emoji: "✎",
            blurb: "Hear a word, then spell it right.", color: 0xC79BB8),
        LairSubject(
            id: "phonics", label: "Phonics", emoji: "🔤",
            blurb: "Every sound in the English code, one at a time.", color: 0xA07859),
        LairSubject(
            id: "memorize", label: "Memorize", emoji: "📖",
            blurb: "Learn a passage by heart, a little at a time.", color: 0x7D9D6C),
    ]
}

extension LairSkillTag {
    /// Every skill tag, in the JavaScript `SKILL_TAGS` order.
    public static let all: [LairSkillTag] = [
        LairSkillTag(id: "add", label: "Addition", symbol: "+",
                     blurb: "sums & totals", color: 0x7D9D6C),
        LairSkillTag(id: "sub", label: "Subtraction", symbol: "−",
                     blurb: "taking away", color: 0x8EB0CC),
        LairSkillTag(id: "mul", label: "Multiplication", symbol: "×",
                     blurb: "times tables", color: 0xD97474),
        LairSkillTag(id: "div", label: "Division", symbol: "÷",
                     blurb: "sharing fairly", color: 0xD4A957),
        LairSkillTag(id: "spelling", label: "Spelling", symbol: "✎",
                     blurb: "", color: 0xC79BB8),
        LairSkillTag(id: "phonics", label: "Phonics", symbol: "🔤",
                     blurb: "", color: 0xA07859),
        LairSkillTag(id: "memorization", label: "Memorization", symbol: "📖",
                     blurb: "", color: 0x7D9D6C),
    ]
}

extension LairGame {
    /// Every lair game, in the JavaScript `GAME_TYPES` order. `premium` is
    /// membership of `PAID_GAME_IDS`.
    public static let all: [LairGame] = [
        LairGame(
            id: "dragon-egg-hatchery", subject: "math", name: "Dragon Egg Hatchery", emoji: "🥚",
            description: "Help dragon eggs hatch by solving facts quickly!",
            skills: [.add, .sub, .mul, .div], practices: ["add", "sub", "mul", "div"],
            hasOwnPage: false, premium: false),
        LairGame(
            id: "dragon-munchers", subject: "math", name: "Dragon Munchers", emoji: "🐉",
            description: "Navigate the grid and avoid the dragons! Keep your muncher safe.",
            skills: [.mul], practices: ["mul"],
            hasOwnPage: false, premium: true),
        LairGame(
            id: "stepping-stones", subject: "math", name: "Stepping Stones", emoji: "🪨",
            description: "Cross the river by tapping lily pads in skip-counting order!",
            skills: [.mul], practices: ["mul"],
            hasOwnPage: false, premium: false),
        LairGame(
            id: "proving-grounds", subject: "math", name: "Proving Grounds", emoji: "🏆",
            description: "Prove your × and ÷ facts against the clock — earn bronze, silver, or gold!",
            skills: [], practices: ["mul", "div"],
            hasOwnPage: true, premium: true),
        LairGame(
            id: "dragon-spelling", subject: "spelling", name: "Dragon Spelling", emoji: "🐲",
            description: "Listen to a word, then spell it! Pick your grade and level.",
            skills: [], practices: ["spelling"],
            hasOwnPage: true, premium: true),
        LairGame(
            id: "dragon-phonics", subject: "phonics", name: "Dragon Phonics", emoji: "🔤",
            description: "Listen to a word, then tap the missing sound! Vowels, blends, and more.",
            skills: [], practices: ["phonics"],
            hasOwnPage: true, premium: false),
        LairGame(
            id: "dragon-memorize", subject: "memorize", name: "Dragon Memorize", emoji: "📖",
            description: "Learn passages a little at a time, then recall every word!",
            skills: [], practices: ["memorization"],
            hasOwnPage: true, premium: false),
    ]
}
