// GENERATED by scripts/generate-swift-map-data.mjs from src/data/mapData.js
// and ios/ArtExports/manifest.json — do not edit by hand. Run
// `npm run ios:map-data` after changing the map or re-exporting the art.

extension GameMap {
    /// The map's width in map coordinates (the web's SVG viewBox).
    public static let width: Double = 400

    /// The worlds the app shows, first to last (bottom of the map to top).
    public static let worlds: [MapWorld] = [
        MapWorld(
            id: 1, name: "Mushroom Forest", chapterHeading: "~ chapter one ~",
            nodeIDs: 1...8,
            chapterCenter: MapPoint(x: 260, y: 5551), chapterColor: 0x7D9D6C,
            bandTop: 4805, bandBottom: 5700,
            background: MapArtTile(name: "MapWorld1Background", top: 4805, height: 895),
            road: MapArtTile(name: "MapWorld1Road", top: 4805, height: 895)
        ),
        MapWorld(
            id: 2, name: "Honeyfield Plains", chapterHeading: "~ chapter two ~",
            nodeIDs: 9...16,
            chapterCenter: MapPoint(x: 295, y: 4671), chapterColor: 0xB8852F,
            bandTop: 3905, bandBottom: 4805,
            background: MapArtTile(name: "MapWorld2Background", top: 3905, height: 900),
            road: MapArtTile(name: "MapWorld2Road", top: 3905, height: 900)
        ),
        MapWorld(
            id: 3, name: "Crystal Caves", chapterHeading: "~ chapter three ~",
            nodeIDs: 17...25,
            chapterCenter: MapPoint(x: 295, y: 3771), chapterColor: 0x9D7FC4,
            bandTop: 2895, bandBottom: 3905,
            background: MapArtTile(name: "MapWorld3Background", top: 2895, height: 1010),
            road: MapArtTile(name: "MapWorld3Road", top: 2895, height: 1010)
        ),
        MapWorld(
            id: 4, name: "Sakura Vale", chapterHeading: "~ chapter four ~",
            nodeIDs: 26...33,
            chapterCenter: MapPoint(x: 295, y: 2761), chapterColor: 0xC78AA6,
            bandTop: 1995, bandBottom: 2895,
            background: MapArtTile(name: "MapWorld4Background", top: 1995, height: 900),
            road: MapArtTile(name: "MapWorld4Road", top: 1995, height: 900)
        ),
        MapWorld(
            id: 5, name: "Cloudspire Heights", chapterHeading: "~ chapter five ~",
            nodeIDs: 34...41,
            chapterCenter: MapPoint(x: 295, y: 1861), chapterColor: 0x7FA6C4,
            bandTop: 1000, bandBottom: 1995,
            background: MapArtTile(name: "MapWorld5Background", top: 1000, height: 995),
            road: MapArtTile(name: "MapWorld5Road", top: 1000, height: 995)
        ),
    ]

    /// Every node on those worlds, in play order.
    public static let nodes: [MapNode] = [
        MapNode(id: 1, kind: .regular, label: "Meadow Gate", icon: "🏡", position: MapPoint(x: 200, y: 5640), worldID: 1),
        MapNode(id: 2, kind: .regular, label: "Firefly Glen", icon: "🌿", position: MapPoint(x: 110, y: 5530), worldID: 1),
        MapNode(id: 3, kind: .regular, label: "Toadstool Inn", icon: "🍄", position: MapPoint(x: 270, y: 5420), worldID: 1),
        MapNode(id: 4, kind: .regular, label: "Mossy Tower", icon: "🗼", position: MapPoint(x: 120, y: 5310), worldID: 1),
        MapNode(id: 5, kind: .regular, label: "Dewdrop Pond", icon: "💧", position: MapPoint(x: 260, y: 5200), worldID: 1),
        MapNode(id: 6, kind: .regular, label: "Spore Hollow", icon: "🌑", position: MapPoint(x: 115, y: 5090), worldID: 1),
        MapNode(id: 7, kind: .regular, label: "Hedgehog Hollow", icon: "🦔", position: MapPoint(x: 265, y: 4980), worldID: 1),
        MapNode(id: 8, kind: .boss, label: "Forest Dragon", icon: "🐲", position: MapPoint(x: 200, y: 4870), worldID: 1, bossArt: "BossForestDragon"),
        MapNode(id: 9, kind: .regular, label: "Sunflower Field", icon: "🌻", position: MapPoint(x: 200, y: 4740), worldID: 2),
        MapNode(id: 10, kind: .regular, label: "Honeycomb Hive", icon: "🍯", position: MapPoint(x: 110, y: 4630), worldID: 2),
        MapNode(id: 11, kind: .regular, label: "Butterfly Bridge", icon: "🦋", position: MapPoint(x: 270, y: 4520), worldID: 2),
        MapNode(id: 12, kind: .regular, label: "Beekeeper's Cottage", icon: "🏡", position: MapPoint(x: 120, y: 4410), worldID: 2),
        MapNode(id: 13, kind: .regular, label: "Wildflower Knoll", icon: "🌼", position: MapPoint(x: 260, y: 4300), worldID: 2),
        MapNode(id: 14, kind: .regular, label: "Golden Pond", icon: "🦆", position: MapPoint(x: 115, y: 4190), worldID: 2),
        MapNode(id: 15, kind: .regular, label: "Lark's Hollow", icon: "🐦", position: MapPoint(x: 265, y: 4080), worldID: 2),
        MapNode(id: 16, kind: .boss, label: "Sunfire Dragon", icon: "🐲", position: MapPoint(x: 200, y: 3970), worldID: 2, bossArt: "BossSunfireDragon"),
        MapNode(id: 17, kind: .regular, label: "Crystal Pass", icon: "💎", position: MapPoint(x: 200, y: 3840), worldID: 3),
        MapNode(id: 18, kind: .regular, label: "Gem Grotto", icon: "🔮", position: MapPoint(x: 115, y: 3730), worldID: 3),
        MapNode(id: 19, kind: .regular, label: "Prism Falls", icon: "🌊", position: MapPoint(x: 265, y: 3620), worldID: 3),
        MapNode(id: 20, kind: .regular, label: "Echo Chamber", icon: "🗿", position: MapPoint(x: 120, y: 3510), worldID: 3),
        MapNode(id: 21, kind: .regular, label: "Sapphire Mine", icon: "⛏️", position: MapPoint(x: 260, y: 3400), worldID: 3),
        MapNode(id: 22, kind: .regular, label: "Ice Pinnacle", icon: "❄️", position: MapPoint(x: 125, y: 3290), worldID: 3),
        MapNode(id: 23, kind: .regular, label: "Moon Shrine", icon: "🌙", position: MapPoint(x: 255, y: 3180), worldID: 3),
        MapNode(id: 24, kind: .regular, label: "Star Garden", icon: "⭐", position: MapPoint(x: 170, y: 3070), worldID: 3),
        MapNode(id: 25, kind: .boss, label: "Crystal Dragon", icon: "🐉", position: MapPoint(x: 200, y: 2960), worldID: 3, bossArt: "BossCrystalDragon"),
        MapNode(id: 26, kind: .regular, label: "Petal Path", icon: "🌸", position: MapPoint(x: 200, y: 2830), worldID: 4),
        MapNode(id: 27, kind: .regular, label: "Koi Pond", icon: "🐟", position: MapPoint(x: 110, y: 2720), worldID: 4),
        MapNode(id: 28, kind: .regular, label: "Lantern Bridge", icon: "🏮", position: MapPoint(x: 270, y: 2610), worldID: 4),
        MapNode(id: 29, kind: .regular, label: "Tea Pavilion", icon: "🍵", position: MapPoint(x: 120, y: 2500), worldID: 4),
        MapNode(id: 30, kind: .regular, label: "Bamboo Grove", icon: "🎋", position: MapPoint(x: 260, y: 2390), worldID: 4),
        MapNode(id: 31, kind: .regular, label: "Crane's Roost", icon: "🕊️", position: MapPoint(x: 115, y: 2280), worldID: 4),
        MapNode(id: 32, kind: .regular, label: "Misty Summit", icon: "⛰️", position: MapPoint(x: 265, y: 2170), worldID: 4),
        MapNode(id: 33, kind: .boss, label: "Sakura Dragon", icon: "🐲", position: MapPoint(x: 200, y: 2060), worldID: 4, bossArt: "BossSakuraDragon"),
        MapNode(id: 34, kind: .regular, label: "Cloud Landing", icon: "☁️", position: MapPoint(x: 200, y: 1930), worldID: 5),
        MapNode(id: 35, kind: .regular, label: "Rainbow Span", icon: "🌈", position: MapPoint(x: 110, y: 1820), worldID: 5),
        MapNode(id: 36, kind: .regular, label: "Wishing-Star Steps", icon: "✨", position: MapPoint(x: 270, y: 1710), worldID: 5),
        MapNode(id: 37, kind: .regular, label: "Pegasus Glade", icon: "🦄", position: MapPoint(x: 120, y: 1600), worldID: 5),
        MapNode(id: 38, kind: .regular, label: "Windchime Bluff", icon: "🎐", position: MapPoint(x: 260, y: 1490), worldID: 5),
        MapNode(id: 39, kind: .regular, label: "Aurora Tower", icon: "🗼", position: MapPoint(x: 115, y: 1380), worldID: 5),
        MapNode(id: 40, kind: .regular, label: "Zephyr Peak", icon: "🪁", position: MapPoint(x: 265, y: 1270), worldID: 5),
        MapNode(id: 41, kind: .boss, label: "Storm Dragon", icon: "🐉", position: MapPoint(x: 200, y: 1160), worldID: 5, bossArt: "BossStormDragon"),
    ]
}
