// GENERATED by scripts/generate-swift-phonics-data.mjs from
// src/data/phonicsCurriculum.js, phonicsRounds.js and phonicsWords.js — do not
// edit by hand. Run `npm run ios:phonics-data` after changing them.

extension PhonicsElement {
    /// Every element, in the JavaScript `PHONICS_ELEMENTS` order.
    public static let all: [PhonicsElement] = [
        PhonicsElement(
            key: "b", g: "b", sound: "/b/", type: "consonant", stage: 1,
            words: ["bat", "bee", "bud"], near: ["d", "p"], accepts: ["b"],
            note: ""),
        PhonicsElement(
            key: "c", g: "c", sound: "/k/", type: "consonant", stage: 1,
            words: ["cat", "cub", "cap"], near: ["k", "g"], accepts: ["c", "k"],
            note: ""),
        PhonicsElement(
            key: "d", g: "d", sound: "/d/", type: "consonant", stage: 1,
            words: ["dog", "den", "dig"], near: ["b", "t"], accepts: ["d"],
            note: ""),
        PhonicsElement(
            key: "f", g: "f", sound: "/f/", type: "consonant", stage: 1,
            words: ["fox", "fig", "fan"], near: ["v", "ph"], accepts: ["f"],
            note: ""),
        PhonicsElement(
            key: "g", g: "g", sound: "/g/", type: "consonant", stage: 1,
            words: ["goat", "gum", "gap"], near: ["c", "k"], accepts: ["g"],
            note: ""),
        PhonicsElement(
            key: "h", g: "h", sound: "/h/", type: "consonant", stage: 1,
            words: ["hen", "hop", "hug"], near: ["f"], accepts: ["h"],
            note: ""),
        PhonicsElement(
            key: "j", g: "j", sound: "/j/", type: "consonant", stage: 1,
            words: ["jam", "jet", "jug"], near: ["g", "ch"], accepts: ["j"],
            note: ""),
        PhonicsElement(
            key: "k", g: "k", sound: "/k/", type: "consonant", stage: 1,
            words: ["kid", "kit", "kelp"], near: ["c", "g"], accepts: ["k", "c"],
            note: ""),
        PhonicsElement(
            key: "l", g: "l", sound: "/l/", type: "consonant", stage: 1,
            words: ["leaf", "log", "lip"], near: ["r", "w"], accepts: ["l"],
            note: ""),
        PhonicsElement(
            key: "m", g: "m", sound: "/m/", type: "consonant", stage: 1,
            words: ["moss", "mud", "map"], near: ["n"], accepts: ["m"],
            note: ""),
        PhonicsElement(
            key: "n", g: "n", sound: "/n/", type: "consonant", stage: 1,
            words: ["nest", "nut", "nap"], near: ["m", "ng"], accepts: ["n"],
            note: ""),
        PhonicsElement(
            key: "p", g: "p", sound: "/p/", type: "consonant", stage: 1,
            words: ["pig", "pot", "pup"], near: ["b", "t"], accepts: ["p"],
            note: ""),
        PhonicsElement(
            key: "r", g: "r", sound: "/r/", type: "consonant", stage: 1,
            words: ["rug", "rain", "rock"], near: ["l", "w"], accepts: ["r"],
            note: ""),
        PhonicsElement(
            key: "s", g: "s", sound: "/s/", type: "consonant", stage: 1,
            words: ["sun", "sap", "seed"], near: ["z", "c"], accepts: ["s"],
            note: ""),
        PhonicsElement(
            key: "t", g: "t", sound: "/t/", type: "consonant", stage: 1,
            words: ["top", "ten", "tub"], near: ["d", "p"], accepts: ["t"],
            note: ""),
        PhonicsElement(
            key: "v", g: "v", sound: "/v/", type: "consonant", stage: 1,
            words: ["vine", "van", "vet"], near: ["f"], accepts: ["v"],
            note: ""),
        PhonicsElement(
            key: "w", g: "w", sound: "/w/", type: "consonant", stage: 1,
            words: ["web", "wind", "wag"], near: ["r", "l"], accepts: ["w"],
            note: ""),
        PhonicsElement(
            key: "y", g: "y", sound: "/y/", type: "consonant", stage: 1,
            words: ["yak", "yarn", "yes"], near: ["j", "w"], accepts: ["y"],
            note: ""),
        PhonicsElement(
            key: "z", g: "z", sound: "/z/", type: "consonant", stage: 1,
            words: ["zip", "zebra", "zoo"], near: ["s"], accepts: ["z"],
            note: ""),
        PhonicsElement(
            key: "qu", g: "qu", sound: "/kw/", type: "consonant", stage: 1,
            words: ["quilt", "queen", "quick"], near: ["c", "k"], accepts: ["qu"],
            note: ""),
        PhonicsElement(
            key: "x", g: "x", sound: "/ks/", type: "consonant", stage: 1,
            words: ["fox", "box", "six"], near: ["s", "k"], accepts: ["x"],
            note: "x sits at the END of these words"),
        PhonicsElement(
            key: "short-a", g: "a", sound: "/ă/", type: "short-vowel", stage: 2,
            words: ["cat", "map", "ham"], near: ["short-e", "short-u"], accepts: ["a"],
            note: ""),
        PhonicsElement(
            key: "short-e", g: "e", sound: "/ĕ/", type: "short-vowel", stage: 2,
            words: ["hen", "bed", "nest"], near: ["short-a", "short-i"], accepts: ["e"],
            note: ""),
        PhonicsElement(
            key: "short-i", g: "i", sound: "/ĭ/", type: "short-vowel", stage: 2,
            words: ["pig", "fig", "wind"], near: ["short-e", "short-u"], accepts: ["i"],
            note: ""),
        PhonicsElement(
            key: "short-o", g: "o", sound: "/ŏ/", type: "short-vowel", stage: 2,
            words: ["dog", "pot", "frog"], near: ["short-u", "short-a"], accepts: ["o"],
            note: ""),
        PhonicsElement(
            key: "short-u", g: "u", sound: "/ŭ/", type: "short-vowel", stage: 2,
            words: ["sun", "cub", "mud"], near: ["short-o", "short-a"], accepts: ["u"],
            note: ""),
        PhonicsElement(
            key: "sh", g: "sh", sound: "/sh/", type: "digraph", stage: 3,
            words: ["ship", "shell", "fish"], near: ["ch", "th"], accepts: ["sh"],
            note: ""),
        PhonicsElement(
            key: "ch", g: "ch", sound: "/ch/", type: "digraph", stage: 3,
            words: ["chin", "chick", "beach"], near: ["sh", "th"], accepts: ["ch"],
            note: ""),
        PhonicsElement(
            key: "th", g: "th", sound: "/th/", type: "digraph", stage: 3,
            words: ["thin", "bath", "moth"], near: ["sh", "ch"], accepts: ["th"],
            note: ""),
        PhonicsElement(
            key: "wh", g: "wh", sound: "/wh/", type: "digraph", stage: 3,
            words: ["whale", "wheat", "whisk"], near: ["w", "sh"], accepts: ["wh"],
            note: ""),
        PhonicsElement(
            key: "ck", g: "ck", sound: "/k/", type: "digraph", stage: 3,
            words: ["duck", "rock", "sock"], near: ["k", "c"], accepts: ["ck"],
            note: "ck only comes at the END of a word"),
        PhonicsElement(
            key: "ng", g: "ng", sound: "/ng/", type: "digraph", stage: 3,
            words: ["ring", "song", "wing"], near: ["n", "end-nk"], accepts: ["ng"],
            note: ""),
        PhonicsElement(
            key: "ph", g: "ph", sound: "/f/", type: "digraph", stage: 3,
            words: ["phone", "graph", "dolphin"], near: ["f", "th"], accepts: ["ph"],
            note: ""),
        PhonicsElement(
            key: "bl", g: "bl", sound: "/bl/", type: "blend-initial", stage: 4,
            words: ["block", "blue", "blossom"], near: ["br", "pl"], accepts: ["bl"],
            note: ""),
        PhonicsElement(
            key: "br", g: "br", sound: "/br/", type: "blend-initial", stage: 4,
            words: ["brick", "bread", "branch"], near: ["bl", "pr"], accepts: ["br"],
            note: ""),
        PhonicsElement(
            key: "cl", g: "cl", sound: "/cl/", type: "blend-initial", stage: 4,
            words: ["clap", "cloud", "clover"], near: ["cr", "gl"], accepts: ["cl"],
            note: ""),
        PhonicsElement(
            key: "cr", g: "cr", sound: "/cr/", type: "blend-initial", stage: 4,
            words: ["crab", "crown", "cricket"], near: ["cl", "gr"], accepts: ["cr"],
            note: ""),
        PhonicsElement(
            key: "dr", g: "dr", sound: "/dr/", type: "blend-initial", stage: 4,
            words: ["drum", "dress", "dragon"], near: ["tr", "gr"], accepts: ["dr"],
            note: ""),
        PhonicsElement(
            key: "fl", g: "fl", sound: "/fl/", type: "blend-initial", stage: 4,
            words: ["flag", "flower", "float"], near: ["fr", "bl"], accepts: ["fl"],
            note: ""),
        PhonicsElement(
            key: "fr", g: "fr", sound: "/fr/", type: "blend-initial", stage: 4,
            words: ["frog", "fruit", "fresh"], near: ["fl", "thr"], accepts: ["fr"],
            note: ""),
        PhonicsElement(
            key: "gl", g: "gl", sound: "/gl/", type: "blend-initial", stage: 4,
            words: ["glad", "glow", "glass"], near: ["gr", "cl"], accepts: ["gl"],
            note: ""),
        PhonicsElement(
            key: "gr", g: "gr", sound: "/gr/", type: "blend-initial", stage: 4,
            words: ["grass", "green", "grape"], near: ["gl", "cr"], accepts: ["gr"],
            note: ""),
        PhonicsElement(
            key: "pl", g: "pl", sound: "/pl/", type: "blend-initial", stage: 4,
            words: ["plant", "plum", "play"], near: ["pr", "bl"], accepts: ["pl"],
            note: ""),
        PhonicsElement(
            key: "pr", g: "pr", sound: "/pr/", type: "blend-initial", stage: 4,
            words: ["prize", "pretty", "present"], near: ["pl", "br"], accepts: ["pr"],
            note: ""),
        PhonicsElement(
            key: "sl", g: "sl", sound: "/sl/", type: "blend-initial", stage: 4,
            words: ["sled", "sleep", "slow"], near: ["sn", "sw"], accepts: ["sl"],
            note: ""),
        PhonicsElement(
            key: "sc", g: "sc", sound: "/sc/", type: "blend-initial", stage: 4,
            words: ["scarf", "scoop", "scale"], near: ["sk", "st"], accepts: ["sc"],
            note: ""),
        PhonicsElement(
            key: "sk", g: "sk", sound: "/sk/", type: "blend-initial", stage: 4,
            words: ["skip", "sky", "skate"], near: ["sc", "sp"], accepts: ["sk"],
            note: ""),
        PhonicsElement(
            key: "sm", g: "sm", sound: "/sm/", type: "blend-initial", stage: 4,
            words: ["smile", "small", "smell"], near: ["sn", "sl"], accepts: ["sm"],
            note: ""),
        PhonicsElement(
            key: "sn", g: "sn", sound: "/sn/", type: "blend-initial", stage: 4,
            words: ["snail", "snow", "snack"], near: ["sm", "sl"], accepts: ["sn"],
            note: ""),
        PhonicsElement(
            key: "sp", g: "sp", sound: "/sp/", type: "blend-initial", stage: 4,
            words: ["spin", "spoon", "spring"], near: ["st", "sk"], accepts: ["sp"],
            note: ""),
        PhonicsElement(
            key: "st", g: "st", sound: "/st/", type: "blend-initial", stage: 4,
            words: ["stem", "star", "stone"], near: ["sp", "sc"], accepts: ["st"],
            note: ""),
        PhonicsElement(
            key: "sw", g: "sw", sound: "/sw/", type: "blend-initial", stage: 4,
            words: ["swim", "sweet", "swan"], near: ["sl", "sn"], accepts: ["sw"],
            note: ""),
        PhonicsElement(
            key: "tr", g: "tr", sound: "/tr/", type: "blend-initial", stage: 4,
            words: ["tree", "train", "trail"], near: ["dr", "tw"], accepts: ["tr"],
            note: ""),
        PhonicsElement(
            key: "tw", g: "tw", sound: "/tw/", type: "blend-initial", stage: 4,
            words: ["twig", "twin", "twelve"], near: ["tr", "sw"], accepts: ["tw"],
            note: ""),
        PhonicsElement(
            key: "scr", g: "scr", sound: "/scr/", type: "blend-initial", stage: 4,
            words: ["scrub", "scrap", "scramble"], near: ["str", "spr"], accepts: ["scr"],
            note: ""),
        PhonicsElement(
            key: "spl", g: "spl", sound: "/spl/", type: "blend-initial", stage: 4,
            words: ["splash", "split", "splendid"], near: ["spr", "scr"], accepts: ["spl"],
            note: ""),
        PhonicsElement(
            key: "spr", g: "spr", sound: "/spr/", type: "blend-initial", stage: 4,
            words: ["spring", "sprout", "spray"], near: ["scr", "str"], accepts: ["spr"],
            note: ""),
        PhonicsElement(
            key: "str", g: "str", sound: "/str/", type: "blend-initial", stage: 4,
            words: ["string", "straw", "stream"], near: ["scr", "spr"], accepts: ["str"],
            note: ""),
        PhonicsElement(
            key: "thr", g: "thr", sound: "/thr/", type: "blend-initial", stage: 4,
            words: ["three", "throw", "thread"], near: ["fr", "shr"], accepts: ["thr"],
            note: ""),
        PhonicsElement(
            key: "shr", g: "shr", sound: "/shr/", type: "blend-initial", stage: 4,
            words: ["shrub", "shrimp", "shred"], near: ["thr", "str"], accepts: ["shr"],
            note: ""),
        PhonicsElement(
            key: "end-nd", g: "nd", sound: "/nd/", type: "blend-final", stage: 5,
            words: ["hand", "pond", "wind"], near: ["end-nt", "end-nk"], accepts: ["nd"],
            note: ""),
        PhonicsElement(
            key: "end-nt", g: "nt", sound: "/nt/", type: "blend-final", stage: 5,
            words: ["plant", "tent", "ant"], near: ["end-nd", "end-nk"], accepts: ["nt"],
            note: ""),
        PhonicsElement(
            key: "end-nk", g: "nk", sound: "/nk/", type: "blend-final", stage: 5,
            words: ["pink", "trunk", "bank"], near: ["ng", "end-nd"], accepts: ["nk"],
            note: ""),
        PhonicsElement(
            key: "end-mp", g: "mp", sound: "/mp/", type: "blend-final", stage: 5,
            words: ["lamp", "jump", "stump"], near: ["mb", "end-nt"], accepts: ["mp"],
            note: ""),
        PhonicsElement(
            key: "end-st", g: "st", sound: "/st/", type: "blend-final", stage: 5,
            words: ["nest", "mist", "toast"], near: ["end-sk", "end-sp"], accepts: ["st"],
            note: ""),
        PhonicsElement(
            key: "end-sk", g: "sk", sound: "/sk/", type: "blend-final", stage: 5,
            words: ["desk", "mask", "tusk"], near: ["end-st", "end-sp"], accepts: ["sk"],
            note: ""),
        PhonicsElement(
            key: "end-sp", g: "sp", sound: "/sp/", type: "blend-final", stage: 5,
            words: ["wasp", "crisp", "grasp"], near: ["end-st", "end-sk"], accepts: ["sp"],
            note: ""),
        PhonicsElement(
            key: "end-lt", g: "lt", sound: "/lt/", type: "blend-final", stage: 5,
            words: ["melt", "salt", "quilt"], near: ["end-lk", "end-lf"], accepts: ["lt"],
            note: ""),
        PhonicsElement(
            key: "end-lk", g: "lk", sound: "/lk/", type: "blend-final", stage: 5,
            words: ["milk", "elk", "silk"], near: ["end-lt", "end-lf"], accepts: ["lk"],
            note: ""),
        PhonicsElement(
            key: "end-lf", g: "lf", sound: "/lf/", type: "blend-final", stage: 5,
            words: ["elf", "shelf", "wolf"], near: ["end-lt", "end-lk"], accepts: ["lf"],
            note: ""),
        PhonicsElement(
            key: "end-ft", g: "ft", sound: "/ft/", type: "blend-final", stage: 5,
            words: ["gift", "soft", "raft"], near: ["end-lt", "end-st"], accepts: ["ft"],
            note: ""),
        PhonicsElement(
            key: "end-pt", g: "pt", sound: "/pt/", type: "blend-final", stage: 5,
            words: ["kept", "slept", "crept"], near: ["end-ft", "end-ct"], accepts: ["pt"],
            note: ""),
        PhonicsElement(
            key: "end-ct", g: "ct", sound: "/ct/", type: "blend-final", stage: 5,
            words: ["fact", "insect", "protect"], near: ["end-pt", "end-ft"], accepts: ["ct"],
            note: ""),
        PhonicsElement(
            key: "end-nch", g: "nch", sound: "/nch/", type: "blend-final", stage: 5,
            words: ["bench", "branch", "lunch"], near: ["end-nt", "end-tch"], accepts: ["nch"],
            note: ""),
        PhonicsElement(
            key: "end-tch", g: "tch", sound: "/tch/", type: "blend-final", stage: 5,
            words: ["patch", "hutch", "stitch"], near: ["ch", "end-nch"], accepts: ["tch"],
            note: ""),
        PhonicsElement(
            key: "long-a", g: "a_e", sound: "/ā/", type: "long-vowel", stage: 6,
            words: ["cake", "lake", "grape"], near: ["long-e", "short-a"], accepts: ["a_e", "a-e", "ae"],
            note: ""),
        PhonicsElement(
            key: "long-e", g: "e_e", sound: "/ē/", type: "long-vowel", stage: 6,
            words: ["these", "theme", "eve"], near: ["long-a", "long-i"], accepts: ["e_e", "e-e", "ee"],
            note: ""),
        PhonicsElement(
            key: "long-i", g: "i_e", sound: "/ī/", type: "long-vowel", stage: 6,
            words: ["vine", "kite", "smile"], near: ["long-e", "short-i"], accepts: ["i_e", "i-e", "ie"],
            note: ""),
        PhonicsElement(
            key: "long-o", g: "o_e", sound: "/ō/", type: "long-vowel", stage: 6,
            words: ["bone", "stone", "rose"], near: ["long-u", "short-o"], accepts: ["o_e", "o-e", "oe"],
            note: ""),
        PhonicsElement(
            key: "long-u", g: "u_e", sound: "/ū/", type: "long-vowel", stage: 6,
            words: ["cube", "mule", "cute"], near: ["long-o", "short-u"], accepts: ["u_e", "u-e", "ue"],
            note: ""),
        PhonicsElement(
            key: "team-ai", g: "ai", sound: "/ā/", type: "vowel-team", stage: 7,
            words: ["rain", "trail", "hay"], near: ["team-ee", "team-oa"], accepts: ["ai", "ay"],
            note: ""),
        PhonicsElement(
            key: "team-ee", g: "ee", sound: "/ē/", type: "vowel-team", stage: 7,
            words: ["tree", "seed", "leaf"], near: ["team-ai", "team-igh"], accepts: ["ee", "ea"],
            note: ""),
        PhonicsElement(
            key: "team-oa", g: "oa", sound: "/ō/", type: "vowel-team", stage: 7,
            words: ["goat", "boat", "snow"], near: ["team-oo-long", "team-ai"], accepts: ["oa", "ow", "oe"],
            note: ""),
        PhonicsElement(
            key: "team-igh", g: "igh", sound: "/ī/", type: "vowel-team", stage: 7,
            words: ["light", "night", "pie"], near: ["team-ee", "team-oi"], accepts: ["igh", "ie"],
            note: ""),
        PhonicsElement(
            key: "team-oo-long", g: "oo", sound: "/o͞o/", type: "vowel-team", stage: 7,
            words: ["moon", "spoon", "bloom"], near: ["team-oo-short", "team-oa"], accepts: ["oo", "ue", "ew"],
            note: "the \"moon\" sound"),
        PhonicsElement(
            key: "team-oo-short", g: "oo", sound: "/o͝o/", type: "vowel-team", stage: 7,
            words: ["book", "wood", "hook"], near: ["team-oo-long", "short-u"], accepts: ["oo"],
            note: "the \"book\" sound"),
        PhonicsElement(
            key: "team-oi", g: "oi", sound: "/oi/", type: "vowel-team", stage: 7,
            words: ["soil", "coin", "toy"], near: ["team-ou", "team-aw"], accepts: ["oi", "oy"],
            note: ""),
        PhonicsElement(
            key: "team-ou", g: "ou", sound: "/ou/", type: "vowel-team", stage: 7,
            words: ["cloud", "round", "flower"], near: ["team-oi", "team-aw"], accepts: ["ou", "ow"],
            note: ""),
        PhonicsElement(
            key: "team-aw", g: "aw", sound: "/aw/", type: "vowel-team", stage: 7,
            words: ["paw", "straw", "dawn"], near: ["team-ou", "short-o"], accepts: ["aw", "au"],
            note: ""),
        PhonicsElement(
            key: "ar", g: "ar", sound: "/ar/", type: "r-controlled", stage: 8,
            words: ["star", "farm", "barn"], near: ["or", "er"], accepts: ["ar"],
            note: ""),
        PhonicsElement(
            key: "or", g: "or", sound: "/or/", type: "r-controlled", stage: 8,
            words: ["corn", "storm", "horn"], near: ["ar", "er"], accepts: ["or"],
            note: ""),
        PhonicsElement(
            key: "er", g: "er", sound: "/er/", type: "r-controlled", stage: 8,
            words: ["fern", "bird", "turtle"], near: ["ar", "or"], accepts: ["er", "ir", "ur"],
            note: "er, ir and ur all say /er/"),
        PhonicsElement(
            key: "soft-c", g: "c", sound: "/s/", type: "special", stage: 8,
            words: ["city", "ice", "cellar"], near: ["s", "c"], accepts: ["c"],
            note: "c says /s/ before e, i and y"),
        PhonicsElement(
            key: "soft-g", g: "g", sound: "/j/", type: "special", stage: 8,
            words: ["gem", "cage", "giraffe"], near: ["j", "g"], accepts: ["g"],
            note: "g says /j/ before e, i and y"),
        PhonicsElement(
            key: "kn", g: "kn", sound: "/n/", type: "special", stage: 8,
            words: ["knee", "knot", "knit"], near: ["n", "gn"], accepts: ["kn"],
            note: "the k is silent"),
        PhonicsElement(
            key: "wr", g: "wr", sound: "/r/", type: "special", stage: 8,
            words: ["wren", "wrap", "wrist"], near: ["r", "kn"], accepts: ["wr"],
            note: "the w is silent"),
        PhonicsElement(
            key: "mb", g: "mb", sound: "/m/", type: "special", stage: 8,
            words: ["lamb", "comb", "thumb"], near: ["m", "end-mp"], accepts: ["mb"],
            note: "the b is silent"),
        PhonicsElement(
            key: "gn", g: "gn", sound: "/n/", type: "special", stage: 8,
            words: ["gnat", "sign", "gnaw"], near: ["kn", "n"], accepts: ["gn"],
            note: "the g is silent"),
        PhonicsElement(
            key: "ing", g: "ing", sound: "/ing/", type: "ending", stage: 8,
            words: ["singing", "growing", "planting"], near: ["ng", "ed"], accepts: ["ing"],
            note: ""),
        PhonicsElement(
            key: "ed", g: "ed", sound: "/ed/", type: "ending", stage: 8,
            words: ["planted", "hopped", "wagged"], near: ["ing", "d"], accepts: ["ed"],
            note: ""),
        PhonicsElement(
            key: "le", g: "le", sound: "/le/", type: "ending", stage: 8,
            words: ["table", "apple", "turtle"], near: ["ed", "ing"], accepts: ["le"],
            note: ""),
        PhonicsElement(
            key: "tion", g: "tion", sound: "/shun/", type: "ending", stage: 8,
            words: ["station", "motion", "lotion"], near: ["sh", "le"], accepts: ["tion"],
            note: ""),
    ]
}

extension PhonicsStage {
    /// The eight stages, in `PHONICS_STAGES` order.
    public static let all: [PhonicsStage] = [
        PhonicsStage(stage: 1, label: "Letter Sounds", emoji: "🌱", blurb: "Every letter has a sound of its own."),
        PhonicsStage(stage: 2, label: "Short Vowels", emoji: "🐣", blurb: "The five little vowel sounds at the heart of a word."),
        PhonicsStage(stage: 3, label: "Digraphs", emoji: "🍃", blurb: "Two letters that team up to make one brand-new sound."),
        PhonicsStage(stage: 4, label: "Beginning Blends", emoji: "🌤️", blurb: "Two sounds that slide together at the start."),
        PhonicsStage(stage: 5, label: "Ending Blends", emoji: "🪺", blurb: "Two sounds that land together at the end."),
        PhonicsStage(stage: 6, label: "Magic E", emoji: "✨", blurb: "A silent e at the end makes the vowel say its name."),
        PhonicsStage(stage: 7, label: "Vowel Teams", emoji: "🌈", blurb: "Vowels working in pairs — rain, moon, cloud."),
        PhonicsStage(stage: 8, label: "Bossy R & More", emoji: "🐉", blurb: "Bossy r, soft sounds, silent letters and word endings."),
    ]
}

extension PhonicsMode {
    /// The four games, in the `PHONICS_MODES` order the web's picker shows.
    public static let all: [PhonicsMode] = [
        PhonicsMode(
            key: "choose", name: "Sound Match", emoji: "👂", tagline: "Hear a sound, tap the letters",
            blurb: "You hear a sound. Tap the letters that make it. The choices are close together on purpose.",
            difficulty: "easier", skill: "recognition"),
        PhonicsMode(
            key: "type-it", name: "Sound Spell", emoji: "⌨️", tagline: "Hear a sound, type the letters",
            blurb: "You hear a sound and type the letters yourself. Nothing to pick from — you have to know it.",
            difficulty: "harder", skill: "recall"),
        PhonicsMode(
            key: "find-in-word", name: "Sound Hunt", emoji: "🔍", tagline: "Hear a word, find the sound inside",
            blurb: "You hear a whole word. Which of these sounds is hiding inside it?",
            difficulty: "medium", skill: "analysis"),
        PhonicsMode(
            key: "missing-sound", name: "Missing Sound", emoji: "🧩", tagline: "Hear a word, fill the blank",
            blurb: "A word with one sound missing. Listen, then tap the piece that fits.",
            difficulty: "medium", skill: "analysis"),
    ]
}

extension Phonics {
    /// Questions in a round (`QUESTIONS_PER_ROUND`).
    public static let questionsPerRound = 10

    /// The modes `buildRound` deals for (`ROUND_MODES`).
    public static let roundModes: [String] = ["choose", "type-it", "find-in-word"]
}

extension PhonicsLevel {
    /// Missing Sound's levels, in `PHONICS_LEVELS` order.
    public static let all: [PhonicsLevel] = [
        PhonicsLevel(
            key: "vowels", label: "Vowel Sounds", emoji: "🌱", options: 3,
            blurb: "The middle vowel is missing — which one do you hear?",
            words: [
                PhonicsWordEntry(graphemes: ["c", "a", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["d", "o", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["p", "i", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["s", "u", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "e", "d"], blank: 1),
                PhonicsWordEntry(graphemes: ["c", "u", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["h", "a", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "u", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["f", "a", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["j", "a", "m"], blank: 1),
                PhonicsWordEntry(graphemes: ["l", "o", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["m", "u", "d"], blank: 1),
                PhonicsWordEntry(graphemes: ["n", "e", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["p", "o", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["r", "u", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["v", "a", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["w", "e", "b"], blank: 1),
                PhonicsWordEntry(graphemes: ["w", "i", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["z", "i", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "a", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["d", "a", "d"], blank: 1),
                PhonicsWordEntry(graphemes: ["f", "i", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["g", "u", "m"], blank: 1),
                PhonicsWordEntry(graphemes: ["h", "a", "m"], blank: 1),
                PhonicsWordEntry(graphemes: ["h", "e", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["j", "e", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["k", "i", "d"], blank: 1),
                PhonicsWordEntry(graphemes: ["l", "i", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["m", "o", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["n", "u", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["p", "a", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["r", "a", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["t", "a", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "u", "s"], blank: 1),
                PhonicsWordEntry(graphemes: ["c", "u", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["d", "i", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["f", "o", "x"], blank: 1),
                PhonicsWordEntry(graphemes: ["h", "o", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["j", "o", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["k", "i", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["l", "a", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["m", "a", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["n", "a", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["p", "e", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["t", "a", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["f", "i", "t"], blank: 1),
                PhonicsWordEntry(graphemes: ["h", "u", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["t", "o", "p"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "i", "g"], blank: 1),
                PhonicsWordEntry(graphemes: ["r", "e", "d"], blank: 1),
                PhonicsWordEntry(graphemes: ["t", "e", "n"], blank: 1),
                PhonicsWordEntry(graphemes: ["s", "i", "x"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "e", "e"], blank: 1),
                PhonicsWordEntry(graphemes: ["o", "w", "l"], blank: 1),
                PhonicsWordEntry(graphemes: ["s", "a", "p"], blank: 1),
            ]),
        PhonicsLevel(
            key: "edges", label: "First & Last", emoji: "🌟", options: 4,
            blurb: "A beginning or ending sound is missing — tap the one you hear.",
            words: [
                PhonicsWordEntry(graphemes: ["c", "a", "t"], blank: 0),
                PhonicsWordEntry(graphemes: ["d", "o", "g"], blank: 2),
                PhonicsWordEntry(graphemes: ["s", "u", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["b", "e", "d"], blank: 2),
                PhonicsWordEntry(graphemes: ["m", "a", "p"], blank: 0),
                PhonicsWordEntry(graphemes: ["l", "e", "g"], blank: 2),
                PhonicsWordEntry(graphemes: ["c", "u", "p"], blank: 0),
                PhonicsWordEntry(graphemes: ["f", "a", "n"], blank: 2),
                PhonicsWordEntry(graphemes: ["b", "u", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["w", "e", "b"], blank: 2),
                PhonicsWordEntry(graphemes: ["h", "e", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["l", "i", "p"], blank: 2),
                PhonicsWordEntry(graphemes: ["n", "u", "t"], blank: 0),
                PhonicsWordEntry(graphemes: ["p", "o", "t"], blank: 2),
                PhonicsWordEntry(graphemes: ["r", "u", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["v", "a", "n"], blank: 2),
                PhonicsWordEntry(graphemes: ["j", "a", "m"], blank: 0),
                PhonicsWordEntry(graphemes: ["b", "a", "t"], blank: 2),
                PhonicsWordEntry(graphemes: ["f", "o", "x"], blank: 0),
                PhonicsWordEntry(graphemes: ["j", "e", "t"], blank: 2),
                PhonicsWordEntry(graphemes: ["k", "i", "d"], blank: 0),
                PhonicsWordEntry(graphemes: ["m", "o", "p"], blank: 2),
                PhonicsWordEntry(graphemes: ["p", "i", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["r", "a", "t"], blank: 2),
                PhonicsWordEntry(graphemes: ["t", "e", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["g", "u", "m"], blank: 2),
                PhonicsWordEntry(graphemes: ["w", "i", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["b", "u", "s"], blank: 2),
                PhonicsWordEntry(graphemes: ["l", "o", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["h", "a", "t"], blank: 2),
                PhonicsWordEntry(graphemes: ["p", "e", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["b", "e", "l", "l"], blank: 3),
                PhonicsWordEntry(graphemes: ["d", "u", "c", "k"], blank: 0),
                PhonicsWordEntry(graphemes: ["f", "i", "s", "h"], blank: 3),
                PhonicsWordEntry(graphemes: ["s", "o", "c", "k"], blank: 0),
                PhonicsWordEntry(graphemes: ["n", "e", "s", "t"], blank: 3),
                PhonicsWordEntry(graphemes: ["l", "a", "m", "p"], blank: 0),
                PhonicsWordEntry(graphemes: ["h", "a", "n", "d"], blank: 3),
                PhonicsWordEntry(graphemes: ["m", "i", "l", "k"], blank: 0),
                PhonicsWordEntry(graphemes: ["g", "i", "f", "t"], blank: 3),
            ]),
        PhonicsLevel(
            key: "blends", label: "Blends & Digraphs", emoji: "🔥", options: 4,
            blurb: "Two letters make one sound (sh, ch, fr…) — find the missing pair.",
            words: [
                PhonicsWordEntry(graphemes: ["sh", "i", "p"], blank: 0),
                PhonicsWordEntry(graphemes: ["ch", "i", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["th", "i", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["wh", "i", "p"], blank: 0),
                PhonicsWordEntry(graphemes: ["sh", "e", "ll"], blank: 0),
                PhonicsWordEntry(graphemes: ["ch", "e", "s", "t"], blank: 0),
                PhonicsWordEntry(graphemes: ["fr", "o", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["st", "e", "m"], blank: 0),
                PhonicsWordEntry(graphemes: ["bl", "o", "ck"], blank: 0),
                PhonicsWordEntry(graphemes: ["cr", "a", "b"], blank: 0),
                PhonicsWordEntry(graphemes: ["dr", "u", "m"], blank: 0),
                PhonicsWordEntry(graphemes: ["fl", "a", "g"], blank: 0),
                PhonicsWordEntry(graphemes: ["gr", "a", "s", "s"], blank: 0),
                PhonicsWordEntry(graphemes: ["pl", "a", "n", "t"], blank: 0),
                PhonicsWordEntry(graphemes: ["sl", "e", "d"], blank: 0),
                PhonicsWordEntry(graphemes: ["sn", "a", "il"], blank: 0),
                PhonicsWordEntry(graphemes: ["sp", "i", "n"], blank: 0),
                PhonicsWordEntry(graphemes: ["sw", "i", "m"], blank: 0),
                PhonicsWordEntry(graphemes: ["tr", "e", "e"], blank: 0),
                PhonicsWordEntry(graphemes: ["br", "i", "ck"], blank: 0),
                PhonicsWordEntry(graphemes: ["cl", "a", "p"], blank: 0),
                PhonicsWordEntry(graphemes: ["gl", "a", "d"], blank: 0),
                PhonicsWordEntry(graphemes: ["pr", "i", "z", "e"], blank: 0),
                PhonicsWordEntry(graphemes: ["d", "u", "ck"], blank: 2),
                PhonicsWordEntry(graphemes: ["s", "o", "ck"], blank: 2),
                PhonicsWordEntry(graphemes: ["r", "o", "ck"], blank: 2),
                PhonicsWordEntry(graphemes: ["fi", "sh"], blank: 1),
                PhonicsWordEntry(graphemes: ["di", "sh"], blank: 1),
                PhonicsWordEntry(graphemes: ["ba", "th"], blank: 1),
                PhonicsWordEntry(graphemes: ["ri", "ng"], blank: 1),
                PhonicsWordEntry(graphemes: ["ki", "ng"], blank: 1),
                PhonicsWordEntry(graphemes: ["so", "ng"], blank: 1),
                PhonicsWordEntry(graphemes: ["b", "e", "ll"], blank: 2),
                PhonicsWordEntry(graphemes: ["ne", "st"], blank: 1),
                PhonicsWordEntry(graphemes: ["ne", "ck"], blank: 1),
            ]),
    ]

    /// Words in a Missing Sound round (`WORDS_PER_ROUND`).
    public static let wordsPerRound = 10
}
