// GENERATED by scripts/generate-swift-spelling-words.mjs from
// src/data/spellingWords.js and spellingPrompts.js — do not edit by hand. Run
// `npm run ios:spelling-words` after changing the JavaScript catalogs.

extension SpellingGrade {
    /// Every grade, in the JavaScript `SPELLING_GRADES` order, with its words
    /// in `SPELLING_WORDS` order.
    public static let all: [SpellingGrade] = [
        SpellingGrade(grade: 1, label: "Grade 1", words: [
            "cat", "dog", "hat", "run", "big", "red", "box", "cup", "bed", "pig",
            "hot", "top", "map", "pen", "bug", "fan", "jam", "log", "mud", "net",
            "pot", "rug", "van", "web", "wig", "zip", "bat", "cab", "dad", "fig",
            "gum", "ham", "hen", "jet", "kid", "lip", "mom", "nut", "pan", "rat",
            "tan", "wet", "yes", "bus", "cut", "dig", "fox", "gas", "hop", "jog",
            "kit", "lap", "mat", "nap", "pet", "rip", "tap", "fit", "gap", "hug",
            "job", "kick", "lock", "milk", "nest", "pond", "sock", "tent", "wind", "yarn",
            "desk", "frog", "gift", "hand", "jump", "lamp", "mask", "plant", "ramp", "sand",
            "soft", "swim", "drum", "flag", "glad", "grin", "clap", "crab", "drop", "sled",
            "spot", "step", "twin", "vet", "fun", "bell", "doll", "fish", "duck", "ship",
        ]),
        SpellingGrade(grade: 2, label: "Grade 2", words: [
            "about", "after", "again", "animal", "apple", "around", "baby", "balloon", "basket", "because",
            "before", "began", "black", "bring", "brother", "bunny", "butter", "button", "candy", "carry",
            "catch", "chair", "cherry", "chicken", "circle", "class", "clean", "climb", "cloud", "color",
            "corner", "cousin", "crayon", "dragon", "dream", "dress", "drink", "eager", "early", "earth",
            "every", "family", "farmer", "feather", "garden", "giant", "gentle", "grass", "green", "happy",
            "hello", "helper", "honey", "hungry", "jelly", "kitten", "ladder", "lemon", "letter", "little",
            "lucky", "magic", "marble", "market", "mitten", "money", "monkey", "mother", "mountain", "music",
            "never", "number", "ocean", "orange", "paper", "party", "pencil", "penny", "pepper", "picture",
            "pillow", "pocket", "pretty", "pumpkin", "puppy", "purple", "rabbit", "rainbow", "river", "robin",
            "rocket", "sandwich", "seven", "sister", "smile", "snail", "spider", "spring", "summer", "turtle",
        ]),
        SpellingGrade(grade: 3, label: "Grade 3", words: [
            "address", "adventure", "afraid", "afternoon", "airplane", "alphabet", "already", "amazing", "angry", "answer",
            "autumn", "basket", "beautiful", "became", "become", "believe", "between", "birthday", "blanket", "breakfast",
            "breeze", "bridge", "brought", "brownie", "butterfly", "calendar", "camera", "careful", "carpet", "castle",
            "caught", "central", "chapter", "charge", "cheerful", "chimney", "chocolate", "clever", "clothing", "common",
            "compass", "complete", "contest", "costume", "cottage", "country", "courage", "crayon", "crowded", "crystal",
            "curious", "dangerous", "daughter", "decide", "delicious", "describe", "desert", "diamond", "dinner", "dinosaur",
            "distance", "dolphin", "double", "dozen", "eagle", "elephant", "elbow", "empty", "enjoy", "enough",
            "evening", "example", "exercise", "explore", "factory", "famous", "favorite", "feather", "field", "fifteen",
            "finally", "fireplace", "flavor", "forest", "forget", "fortune", "fountain", "fraction", "freckle", "freedom",
            "friendly", "frighten", "gallon", "garbage", "gather", "glacier", "golden", "grateful", "greatest", "guitar",
        ]),
        SpellingGrade(grade: 4, label: "Grade 4", words: [
            "absolute", "accident", "according", "achieve", "activity", "addition", "admire", "advantage", "adventure", "against",
            "agreement", "ancient", "apartment", "appear", "appreciate", "arrange", "arrive", "athlete", "attention", "attitude",
            "audience", "average", "balance", "basement", "beginning", "behavior", "beneath", "benefit", "bicycle", "bottom",
            "boundary", "breathe", "brilliant", "calendar", "cabbage", "captain", "capture", "careless", "ceiling", "celebrate",
            "century", "certain", "challenge", "champion", "chapter", "character", "cheerful", "chimney", "citizen", "climate",
            "collect", "college", "comfort", "command", "community", "company", "compare", "complete", "concert", "condition",
            "confident", "confuse", "connect", "consider", "contain", "continue", "control", "convince", "courage", "creature",
            "crocodile", "curious", "current", "customer", "decision", "decorate", "definite", "deliver", "describe", "desert",
            "detail", "develop", "diamond", "different", "difficult", "direction", "disappear", "discover", "discuss", "distance",
            "divide", "document", "dolphin", "doubt", "drawing", "earnest", "eastern", "education", "effort", "electric",
        ]),
        SpellingGrade(grade: 5, label: "Grade 5", words: [
            "abandon", "absence", "absorb", "abundant", "accomplish", "accurate", "addition", "admiral", "adventure", "advertise",
            "ancestor", "announce", "anxious", "apparent", "appreciate", "appropriate", "architect", "argument", "arrangement", "astonish",
            "atmosphere", "attendance", "available", "awkward", "beautiful", "beneath", "beverage", "boundary", "brilliant", "calculate",
            "campaign", "cancel", "capable", "capacity", "category", "celebrate", "cemetery", "ceremony", "challenge", "championship",
            "character", "chemical", "circular", "citizen", "civilization", "classify", "climate", "cabinet", "column", "combine",
            "comfortable", "commercial", "committee", "communicate", "community", "companion", "comparison", "competition", "complete", "complicated",
            "compose", "concentrate", "conclusion", "concrete", "confident", "congratulate", "connection", "conscience", "consequence", "considerable",
            "consistent", "container", "continent", "continuous", "contribute", "convenient", "convince", "cooperate", "courageous", "creative",
            "criticize", "curiosity", "currency", "decision", "decorate", "dedicate", "definite", "delicate", "delicious", "demonstrate",
            "dependent", "describe", "description", "desperate", "develop", "diameter", "difference", "dignity", "diligent", "disappoint",
        ]),
        SpellingGrade(grade: 6, label: "Grade 6", words: [
            "abbreviate", "abundance", "accommodate", "accompany", "accomplishment", "accumulate", "achievement", "acknowledge", "acquaintance", "adequate",
            "adolescent", "advantageous", "ambitious", "analyze", "anonymous", "anticipate", "apparatus", "appreciation", "apprentice", "arrangement",
            "association", "atmosphere", "attendance", "authority", "autobiography", "available", "beneficial", "bibliography", "boundary", "brilliance",
            "bureaucracy", "calculation", "campaign", "candidate", "catastrophe", "category", "cautious", "characteristic", "circumference", "circumstance",
            "coincidence", "collaborate", "colleague", "commitment", "committee", "communicate", "comparison", "competition", "comprehend", "concentrate",
            "condemn", "conference", "confidential", "conscientious", "consequence", "conservation", "considerable", "consistent", "conspicuous", "constitution",
            "controversy", "convenience", "cooperation", "correspond", "courageous", "criticism", "curiosity", "declaration", "dedication", "definition",
            "deliberate", "demonstrate", "descendant", "description", "desirable", "despair", "deteriorate", "determine", "development", "dictionary",
            "difference", "dimension", "diminish", "diploma", "disappoint", "disastrous", "discipline", "distinguish", "dominant", "dramatic",
            "efficient", "eligible", "eliminate", "embarrass", "emphasize", "encounter", "endeavor", "enormous", "enthusiasm", "environment",
        ]),
    ]
}

extension Spelling {
    /// Words a grade round plays (`WORDS_PER_ROUND`).
    public static let wordsPerRound = 10

    /// Grade words recorded with an example sentence (the keys of
    /// `SPELLING_EXAMPLE_SENTENCES` that are in a catalog): their clip is the
    /// word, the sentence, the word — `prompts/<word>.mp3`.
    public static let promptWords: Set<String> = ["addition", "caught", "ceiling", "conscience", "current", "desert"]
}
