// Builds the iOS app's copy of the map data (issue #134): the Swift source of
// ios/Packages/GameRules/Sources/GameRules/MapNodes.swift, and the String
// Catalog entries for every node name, world name and chapter heading.
//
// Everything comes from src/data/mapData.js, plus the art tile frames and boss
// asset names from ios/ArtExports/manifest.json (`npm run ios:export-art`).
// The app shows the worlds whose every node has a built-in battle config
// (DEFAULT_BATTLE_CONFIGS in src/data/battleData.js, which BattleConfigDefaults
// ports) — worlds 1–5, nodes 1–41. A world added to both joins the app on the
// next `npm run ios:map-data`.
//
// Pure: takes file contents in, returns file contents out. The CLI is
// scripts/generate-swift-map-data.mjs; src/data/mapData.ios.test.js fails when
// the committed files drift from these.
import { DEFAULT_BATTLE_CONFIGS } from '../../src/data/battleData.js';
import { SVG_WIDTH } from '../../src/components/map-paper/paperUtils.js';
import { MAP_NODES, WORLDS, chapterWordForWorld } from '../../src/data/mapData.js';

export const SWIFT_PATH = 'ios/Packages/GameRules/Sources/GameRules/MapNodes.swift';
export const CATALOG_PATH = 'ios/DragonAcademy/Localizable.xcstrings';
export const MANIFEST_PATH = 'ios/ArtExports/manifest.json';

// The worlds (and their nodes) the app shows.
export function iosWorlds() {
  return WORLDS.filter(world => {
    const [first, last] = world.nodeRange;
    for (let id = first; id <= last; id++) {
      if (!DEFAULT_BATTLE_CONFIGS[id]) return false;
    }
    return true;
  });
}

export function iosNodes(worlds = iosWorlds()) {
  return MAP_NODES.filter(node =>
    worlds.some(w => node.id >= w.nodeRange[0] && node.id <= w.nodeRange[1]));
}

export function chapterHeading(world) {
  return `~ chapter ${chapterWordForWorld(world)} ~`;
}

// JSON string escaping is valid Swift string-literal escaping for the
// characters that appear here (quotes, apostrophes, emoji).
const swiftString = value => JSON.stringify(value);
const swiftHex = color => `0x${color.replace('#', '').toUpperCase()}`;

function tile(manifest, name) {
  const asset = manifest.assets.find(a => a.name === name);
  if (!asset) throw new Error(`${name} is not in ${MANIFEST_PATH}; run npm run ios:export-art`);
  const [, top, , height] = asset.viewBox;
  return `MapArtTile(name: ${swiftString(name)}, top: ${top}, height: ${height})`;
}

export function buildSwift(manifestText) {
  const manifest = JSON.parse(manifestText);
  const worlds = iosWorlds();
  const nodes = iosNodes(worlds);
  const bossArt = new Map(
    manifest.assets.filter(a => a.group === 'Bosses').map(a => [a.nodeId, a.name]));

  const worldEntries = worlds.map(world => [
    '        MapWorld(',
    `            id: ${world.id}, name: ${swiftString(world.name)}, chapterHeading: ${swiftString(chapterHeading(world))},`,
    `            nodeIDs: ${world.nodeRange[0]}...${world.nodeRange[1]},`,
    `            chapterCenter: MapPoint(x: ${world.chapterX ?? SVG_WIDTH / 2}, y: ${world.chapterY - 14}), chapterColor: ${swiftHex(world.chapterColor)},`,
    `            bandTop: ${world.bandY.top}, bandBottom: ${world.bandY.bottom},`,
    `            background: ${tile(manifest, `MapWorld${world.id}Background`)},`,
    `            road: ${tile(manifest, `MapWorld${world.id}Road`)}`,
    '        ),',
  ].join('\n'));

  const nodeEntries = nodes.map(node => {
    const world = worlds.find(w => node.id >= w.nodeRange[0] && node.id <= w.nodeRange[1]);
    const art = bossArt.get(node.id);
    const artArg = node.type === 'boss' && art ? `, bossArt: ${swiftString(art)}` : '';
    return `        MapNode(id: ${node.id}, kind: .${node.type}, label: ${swiftString(node.label)}, icon: ${swiftString(node.icon)}, `
      + `position: MapPoint(x: ${node.x}, y: ${node.y}), worldID: ${world.id}${artArg}),`;
  });

  return `// GENERATED by scripts/generate-swift-map-data.mjs from src/data/mapData.js
// and ios/ArtExports/manifest.json — do not edit by hand. Run
// \`npm run ios:map-data\` after changing the map or re-exporting the art.

extension GameMap {
    /// The map's width in map coordinates (the web's SVG viewBox).
    public static let width: Double = ${SVG_WIDTH}

    /// The worlds the app shows, first to last (bottom of the map to top).
    public static let worlds: [MapWorld] = [
${worldEntries.join('\n')}
    ]

    /// Every node on those worlds, in play order.
    public static let nodes: [MapNode] = [
${nodeEntries.join('\n')}
    ]
}
`;
}

// ---------- String Catalog ---------------------------------------------------

// The strings the map shows from its data, with a translator comment each.
export function catalogStrings() {
  const worlds = iosWorlds();
  const strings = [];
  for (const world of worlds) {
    strings.push([world.name, `Name of world ${world.id} on the map.`]);
    strings.push([chapterHeading(world), `Chapter heading above world ${world.id}'s name on the map.`]);
  }
  for (const node of iosNodes(worlds)) {
    strings.push([node.label, `Name of map node ${node.id}.`]);
  }
  return strings;
}

// Adds any missing map string to the catalog (English, as a manual entry, like
// the rest of the catalog) and leaves existing entries — and their
// translations — alone. Returns the catalog text in Xcode's own formatting.
export function updateCatalog(catalogText) {
  const catalog = JSON.parse(catalogText);
  for (const [key, comment] of catalogStrings()) {
    if (catalog.strings[key]) continue;
    catalog.strings[key] = {
      comment,
      extractionState: 'manual',
      localizations: { en: { stringUnit: { state: 'translated', value: key } } },
    };
  }
  const sorted = {};
  for (const key of Object.keys(catalog.strings).sort()) sorted[key] = catalog.strings[key];
  catalog.strings = sorted;
  return formatCatalog(catalog);
}

// Xcode writes .xcstrings as 2-space JSON with " : " between key and value,
// and objects' keys in code-point order.
export function formatCatalog(value) {
  return `${format(value, '')}\n`;
}

function format(value, indent) {
  const inner = `${indent}  `;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[\n${value.map(v => inner + format(v, inner)).join(',\n')}\n${indent}]`;
  }
  if (value && typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    return `{\n${keys.map(k => `${inner}${JSON.stringify(k)} : ${format(value[k], inner)}`).join(',\n')}\n${indent}}`;
  }
  return JSON.stringify(value);
}
