// GENERATED by scripts/generate-swift-font-themes.mjs from
// src/data/fontThemes.js — do not edit by hand. Run
// `npm run ios:font-themes` after changing the JavaScript themes.

extension FontTheme {
    /// Every theme, in the JavaScript `FONT_THEMES` order (the picker's).
    static let all: [FontTheme] = [
        FontTheme(
            id: "handwritten", label: "Handwritten ✍️",
            display: .caveat, body: .patrickHand),
        FontTheme(
            id: "bubbly", label: "Bold & Bubbly 🫧",
            display: .fredoka, body: .nunito),
        FontTheme(
            id: "storybook", label: "Storybook 📖",
            display: .baloo2, body: .quicksand),
        FontTheme(
            id: "clean", label: "Clean & Clear 🔤",
            display: .comicNeue, body: .comicNeue),
    ]

    /// `DEFAULT_FONT_THEME`: the theme for a profile that never chose one.
    static let defaultID = "clean"
}
