import { audioFileFor } from '../data/spellingWords';

// Say a spelling word out loud, trying each candidate audio URL in turn and
// falling back to the browser's built-in speech synthesis if none of them play.
//
// Built-in grade words have one candidate: the static file at
// /audio/spelling/<word>.mp3 pre-generated by scripts/generate-spelling-audio.cjs.
// A custom-list word is handed two by audioUrlsFor(): its generated file from
// the shared server-side cache first, then the static one in case the word also
// happens to live in a grade catalog. Either way, a word with no audio at all
// still gets spoken — that fallback is why generating audio is a quality
// upgrade rather than a hard requirement.
//
// Returns a Promise that resolves once the word has finished playing (or
// immediately if no audio could be produced at all). Caches one Audio element
// per URL so repeated "hear it again" taps are instant.
const audioCache = new Map();

function getAudio(url) {
  let audio = audioCache.get(url);
  if (!audio) {
    audio = new Audio(url);
    audio.preload = 'auto';
    audioCache.set(url, audio);
  }
  return audio;
}

function browserSpeak(word) {
  return new Promise((resolve) => {
    const synth = typeof window !== 'undefined' && window.speechSynthesis;
    if (!synth || typeof SpeechSynthesisUtterance === 'undefined') {
      resolve();
      return;
    }
    synth.cancel(); // stop anything mid-utterance
    const utter = new SpeechSynthesisUtterance(word);
    utter.rate = 0.85; // a touch slow so each sound is clear
    utter.pitch = 1;
    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      resolve();
    };
    utter.onend = finish;
    utter.onerror = finish;
    synth.speak(utter);
    // Safety net: some browsers never fire onend for short utterances.
    setTimeout(finish, 4000);
  });
}

// Play one URL. Resolves true once it finishes, false if it can't be played at
// all (missing file, blocked, decode error) so the caller can try the next one.
function playUrl(url) {
  const audio = getAudio(url);

  return new Promise((resolve) => {
    let settled = false;
    const settle = (ok) => {
      if (settled) return;
      settled = true;
      audio.removeEventListener('ended', onEnded);
      audio.removeEventListener('error', onError);
      resolve(ok);
    };
    const onEnded = () => settle(true);
    const onError = () => settle(false);
    audio.addEventListener('ended', onEnded);
    audio.addEventListener('error', onError);

    try {
      audio.currentTime = 0;
    } catch {
      /* not loaded yet — fine */
    }
    const playback = audio.play();
    if (playback && typeof playback.catch === 'function') {
      // play() rejects when the file is missing/blocked → try the next source.
      playback.catch(() => settle(false));
    }
  });
}

export async function speakWord(word, urls) {
  if (!word) return;
  const candidates = urls?.length ? urls : [audioFileFor(word)];

  // Candidates are ordered by preference, so they're tried one at a time —
  // playing them in parallel would talk over the child.
  for (const url of candidates) {
    if (await playUrl(url)) return;
  }
  await browserSpeak(word);
}

// Warm up the browser voice list (some engines load voices lazily, so the first
// utterance is silent unless we've nudged them). Safe to call on game start.
export function primeSpeech() {
  try {
    window.speechSynthesis?.getVoices();
  } catch {
    /* no-op */
  }
}
