// ElevenLabs text-to-speech for CUSTOM spelling-list words, cached in Postgres.
//
// Why the DB and not a file: nginx serves the release symlink's dist/ directory
// (docs/NGINX.md), so anything written to public/ at runtime is thrown away by
// the next deploy. The bytes live in `spelling_audio` instead and are streamed
// by GET /api/spelling/audio/<word>.mp3.
//
// The cache is GLOBAL and keyed by (word, voice) — never by user or list. A word
// is generated once for the whole site and every account that ever puts it on a
// list reuses that MP3, so the hundredth family to add "beautiful" costs nothing.
// For the same reason rows are never deleted along with a list: an English word
// stays useful to everybody, and one row is ~15KB.
//
// The built-in grade catalogs are NOT served from here — those are static files
// pre-generated by scripts/generate-spelling-audio.cjs into public/audio/spelling/.
// The offline catalog intentionally has its own static voice setting: existing
// grade files are Sarah, while custom lists use the runtime voice configured
// below (currently Talia). The model/output settings remain aligned.

const { and, eq, inArray, isNotNull, isNull } = require('drizzle-orm');
const { db, schema } = require('../db');
const { exampleSentencesFor } = require('./spellingContext');

const API_KEY = process.env.ELEVENLABS_API_KEY || '';
const VOICE_ID = process.env.ELEVENLABS_VOICE_ID || 'EXAVITQu4vr4xnSDxMaL'; // "Sarah"
// An English model matters for context-free single words: multilingual_v2 has no
// language anchor and drifts to continental vowels ("van" → "vawn").
const MODEL_ID = process.env.ELEVENLABS_MODEL_ID || 'eleven_turbo_v2';
const OUTPUT_FORMAT = 'mp3_44100_128';

// How many words to generate at once. Sequential-with-a-delay (what the offline
// script does) would make a 15-word save take ~20s of the parent staring at a
// spinner; 3 at a time lands it around 5s without hammering the API.
const CONCURRENCY = 3;

// Per-word ceiling. A slow generation must not hold the save open forever.
const REQUEST_TIMEOUT_MS = 20000;

// Refuse anything implausible as a single spoken word before spending a call.
const MAX_WORD_LEN = 24;

const AUDIO_ENABLED = !!API_KEY;

// A trailing period makes ElevenLabs read a bare word as a clean statement
// rather than a clipped fragment.
function spokenText(word, exampleSentence = null) {
  return exampleSentence
    ? `${word}. ${exampleSentence} ${word}.`
    : `${word}.`;
}

async function ttsToBuffer(word, exampleSentence) {
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}?output_format=${OUTPUT_FORMAT}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'xi-api-key': API_KEY,
      'Content-Type': 'application/json',
      Accept: 'audio/mpeg',
    },
    body: JSON.stringify({
      text: spokenText(word, exampleSentence),
      model_id: MODEL_ID,
      voice_settings: { stability: 0.5, similarity_boost: 0.75, speed: 0.9 },
    }),
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => '');
    throw new Error(`ElevenLabs ${res.status} ${res.statusText} — ${detail.slice(0, 200)}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.length === 0) throw new Error('ElevenLabs returned an empty body');
  return buf;
}

// Which of `words` already have audio for the current voice.
async function cachedWords(words) {
  if (words.length === 0) return new Set();
  const rows = await db
    .select({ word: schema.spellingAudio.word })
    .from(schema.spellingAudio)
    .where(and(
      eq(schema.spellingAudio.voiceId, VOICE_ID),
      inArray(schema.spellingAudio.word, words),
      isNotNull(schema.spellingAudio.mp3),
    ));
  return new Set(rows.map((r) => r.word));
}

async function promptRows(words) {
  if (words.length === 0) return [];
  return db
    .select({
      word: schema.spellingAudio.word,
      mp3: schema.spellingAudio.mp3,
      exampleSentence: schema.spellingAudio.exampleSentence,
      contextCheckedAt: schema.spellingAudio.contextCheckedAt,
    })
    .from(schema.spellingAudio)
    .where(and(
      eq(schema.spellingAudio.voiceId, VOICE_ID),
      inArray(schema.spellingAudio.word, words),
    ));
}

// Sentences are returned with list payloads so browser speech can deliver the
// same prompt when its recorded MP3 is unavailable.
async function cachedPrompts(words) {
  const rows = await promptRows(words);
  return Object.fromEntries(
    rows
      .filter((row) => row.exampleSentence)
      .map((row) => [row.word, row.exampleSentence]),
  );
}

async function uncheckedContextWords(words) {
  const rows = await promptRows(words);
  const checked = new Set(
    rows.filter((row) => row.contextCheckedAt).map((row) => row.word),
  );
  return new Set(words.filter((word) => !checked.has(word)));
}

async function cachePromptWithoutAudio(word, sentence, old) {
  const checkedAt = new Date();
  if (!old) {
    await db
      .insert(schema.spellingAudio)
      .values({
        word,
        voiceId: VOICE_ID,
        mp3: null,
        byteLength: 0,
        exampleSentence: sentence,
        contextCheckedAt: checkedAt,
      })
      .onConflictDoNothing();
    return;
  }

  // Replace a legacy word-only recording with browser fallback rather than let
  // it omit required context. The NULL predicate avoids clobbering an MP3 that
  // another cluster worker successfully upgraded after our initial read.
  await db
    .update(schema.spellingAudio)
    .set({
      mp3: null,
      byteLength: 0,
      exampleSentence: sentence,
      contextCheckedAt: checkedAt,
    })
    .where(and(
      eq(schema.spellingAudio.word, word),
      eq(schema.spellingAudio.voiceId, VOICE_ID),
      isNull(schema.spellingAudio.contextCheckedAt),
    ));
}

/**
 * Make sure every word in `words` has audio in the shared cache, generating the
 * ones that don't.
 *
 * Never throws: a word that fails (bad key, API outage, rate limit) is reported
 * in `failed` and the game simply falls back to the browser's built-in speech
 * for it, exactly as it does today for a word whose file hasn't been generated.
 * Saving a list must never be blocked by a text-to-speech problem.
 *
 * @param {string[]} words  lowercased, already validated
 * @returns {Promise<{ ready: string[], failed: {word: string, error: string}[],
 *                     generated: number, reused: number, enabled: boolean,
 *                     sentences: Record<string, string> }>}
 */
async function ensureAudio(words) {
  const unique = [...new Set(words.filter((w) => w && w.length <= MAX_WORD_LEN))];
  const existing = await promptRows(unique);
  const byWord = new Map(existing.map((row) => [row.word, row]));
  const unchecked = unique.filter((word) => !byWord.get(word)?.contextCheckedAt);
  const uncheckedSet = new Set(unchecked);
  const context = await exampleSentencesFor(unchecked);

  const result = {
    ready: [],
    failed: [],
    generated: 0,
    reused: 0,
    enabled: AUDIO_ENABLED,
    sentences: {},
  };

  // Fixed-size worker pool. A previously cached word can still need work: old
  // rows predate the context check, and an ambiguous one needs its MP3 replaced
  // with the complete word/sentence/word prompt.
  const queue = [...unique];
  const workers = Array.from({ length: Math.min(CONCURRENCY, queue.length) }, async () => {
    for (;;) {
      const word = queue.shift();
      if (word === undefined) return;
      const old = byWord.get(word);
      const wasCheckedNow = context.checked && uncheckedSet.has(word);
      const sentence = wasCheckedNow
        ? (context.sentences.get(word) || null)
        : (old?.exampleSentence || null);
      const promptChanged = wasCheckedNow && sentence !== (old?.exampleSentence || null);
      const needsAudio = !old?.mp3 || promptChanged;

      if (!needsAudio) {
        if (wasCheckedNow) {
          await db
            .update(schema.spellingAudio)
            .set({ exampleSentence: sentence, contextCheckedAt: new Date() })
            .where(and(
              eq(schema.spellingAudio.word, word),
              eq(schema.spellingAudio.voiceId, VOICE_ID),
            ));
        }
        result.ready.push(word);
        result.reused += 1;
        continue;
      }

      if (!AUDIO_ENABLED) {
        // With no MP3, the endpoint returns 404 and the browser speaks the same
        // contextual prompt. A later backfill fills in the ElevenLabs bytes.
        if (wasCheckedNow) await cachePromptWithoutAudio(word, sentence, old);
        result.failed.push({ word, error: 'text-to-speech is not configured' });
        continue;
      }

      try {
        const mp3 = await ttsToBuffer(word, sentence);
        await db
          .insert(schema.spellingAudio)
          .values({
            word,
            voiceId: VOICE_ID,
            mp3,
            byteLength: mp3.length,
            exampleSentence: sentence,
            contextCheckedAt: wasCheckedNow ? new Date() : old?.contextCheckedAt,
          })
          .onConflictDoUpdate({
            target: [schema.spellingAudio.word, schema.spellingAudio.voiceId],
            set: {
              mp3,
              byteLength: mp3.length,
              exampleSentence: sentence,
              ...(wasCheckedNow ? { contextCheckedAt: new Date() } : {}),
            },
          });
        result.ready.push(word);
        result.generated += 1;
      } catch (err) {
        const message = err?.message || String(err);
        console.error(`[spelling-audio] "${word}" failed:`, message);
        // Preserve the AI decision even when ElevenLabs is down. The browser
        // then speaks the full prompt and a later backfill fills in the bytes.
        if (wasCheckedNow) {
          try {
            await cachePromptWithoutAudio(word, sentence, old);
          } catch (cacheErr) {
            console.error(`[spelling-audio] could not cache "${word}" context:`, cacheErr?.message || cacheErr);
          }
        }
        result.failed.push({ word, error: message });
      }
    }
  });
  await Promise.all(workers);

  result.sentences = await cachedPrompts(unique);

  return result;
}

/**
 * Fetch one cached MP3 for playback.
 * @returns {Promise<{ mp3: Buffer, byteLength: number } | null>}
 */
async function getAudio(word) {
  const [row] = await db
    .select({ mp3: schema.spellingAudio.mp3, byteLength: schema.spellingAudio.byteLength })
    .from(schema.spellingAudio)
    .where(and(
      eq(schema.spellingAudio.word, word),
      eq(schema.spellingAudio.voiceId, VOICE_ID),
    ))
    .limit(1);
  if (!row?.mp3) return null;
  return { mp3: row.mp3, byteLength: row.byteLength || row.mp3.length };
}

module.exports = {
  AUDIO_ENABLED,
  VOICE_ID,
  MODEL_ID,
  ensureAudio,
  cachedWords,
  cachedPrompts,
  uncheckedContextWords,
  getAudio,
  spokenText,
};
